"""add Department

Revision ID: 156103d2a55b
Revises: 3e3dfa3206ee
Create Date: 2024-04-05 19:37:07.949877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '156103d2a55b'
down_revision = '3e3dfa3206ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
