"""rename address

Revision ID: 9d7bb52b7cd6
Revises: 5e79a76cd1bb
Create Date: 2024-04-05 22:31:48.770621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d7bb52b7cd6'
down_revision = '5e79a76cd1bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###